### ISSUE TITLE
Logging module import error

### ISSUE THREAD

**Issue by reederda** [gaz492/cachet-monitor#5]
I'm running into an issue setting this up- I installed the "colorama" and "requests" modules via pip when it asked for them. Then, when I ran "python cachetMonitor.py" I received the following error:
"AttributeError: 'module' object has no attribute 'getLogger'

**Comment by bosn181** [comment]
I am getting the same error:

`# python /usr/local/bin/cachet-monitor/system/cachetMonitor.py
Traceback (most recent call last):
  File "/usr/local/bin/cachet-monitor/system/cachetMonitor.py", line 4, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/dist-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
  File "/usr/lib/python2.7/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 35, in <module>
    from .connection import (
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 43, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python2.7/dist-packages/urllib3/util/__init__.py", line 19, in <module>
    from .retry import Retry
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 15, in <module>
    log = logging.getLogger(__name__)
AttributeError: 'module' object has no attribute 'getLogger'`

**Comment by LordCheta** [comment]
Please has anyone fixed this issue?

**Comment by alexdatadesign** [comment]
python run.py from root of the repo.
